### PR TITLE
Boticário Group Practice Test

### PR DESCRIPTION
**Pull request by GH-Marc**
Vamoo ihuu!

### CODE REVIEW

**Review by minhadona — CHANGES_REQUESTED** [review]
HI! Perfect PR! ୧((#Φ益Φ#))୨ 

Just missing the mandatory csv files to complete the challenge! 
These files are available on original repository, you can add to this same commit and request a new approval just after! <3 

take them from here: https://github.com/leivio/work-at-boticario/tree/main/data


I'll be waiting!
Thank you!!!!

**Comment by minhadona** [comment]
Hey, where's the data ? 
You must just copy from original source and paste inside your folder to update the PR, so I can accept and merge it @GH-Marc

**Comment by minhadona** [comment]
Co-authored-by: minhadona <hemitartaratodezolpidem@gmail.com>

**Comment by GH-Marc** [comment]
Hey.

Apologies for the delay! I updated with the missing data.

Can you check now?

**Review by minhadona — APPROVED** [review]

**Pull request merged**
